[Workbench] Workbench.shutdown() doesn't complete due to exception